### ISSUE TITLE
Raspberry Pi Imager point of contact

### ISSUE THREAD

**Issue by tdewey-rpi** [moode-player/imgbuild#3]
Since the release of Raspberry Pi Imager v1.8.1, I've introduced a policy of requiring a named point of contact for OS images we offer.

I've been unable to find a point of contact (name, e-mail address) for Moode - while I could infer a name, I can't infer an e-mail address.

Could you please contact me through the Raspberry Pi Contact page (to avoid public disclosure of e-mail addresses): https://www.raspberrypi.com/contact/

If I cannot identify a point of contact before February 7th 2024 I will be forced to remove Moode from the Image List, and Moode will need to fill out the 'Request an addition to the OS list' form.

**Comment by moodeaudio** [comment]
Sure, no prob. I just sent in the Contact form.
